### ISSUE TITLE
Add `show` options from `d3graph`

### ISSUE THREAD

**Issue by saikumarmk** [snehankekre/streamlit-d3graph#2]
Hello,

I've noticed that your `show` method has the signature:

```
def show(self, figsize=(800, 800), title="d3graph", filepath=io.BytesIO())
```

Whereas the `show` method of the class it inherits from is:

```
show(self, figsize: Tuple[int, int] = (1500, 800), title: str = 'd3graph', filepath: str = 'd3graph.html',
             showfig: bool = True, overwrite: bool = True, show_slider: bool = True)
```

Allowing more options. I'm mainly interested in the `show_slider` option as I don't need a slider on my graph. Was there any reason for not including these extra arguments, or would it be easy to contribute a PR to add them in?

**Comment by snehankekre** [comment]
The initial implementation was naive and very lacking. It has since been fixed by #4.
